language: rust

env:
  global:
    - secure: hdvu4EPy8iJMrvACGQNsHcBaAnRYp8NbxH6a+Q/H4af2kRAgjqFLGU9PzSuFvx+YARgg0guX1y0lFle6+cvRGveB1qqAftEtuEjdYOhVvipgjY6SzyyJhfJYNNTYcvLyyzWWU6lSIWMysVdPPNdQywkjCXeiI/peLBHCrc1CMyQ=

install:
  - make deps

script:
  - rustc -v
  - cargo test
  - cd libnanomsg && cargo test
  - cargo doc

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
  
after_script:
    - mv target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
env:
  global:
    - secure: "SSe9EK+/yXgvij1L4kOc7r5Wcx14sbkBkwsk5B2ajiaeIBu5ePBmQ73WZEUw8wF7J7lGKYcHe7gdvbN/r6ag9aTJc1M7R11jjnyNvMI0Eay/8RmW32Zmwmvu7EDUm3kdWZ7EjzB1vd7AWUOeZr1Gt5vHZLiisxIOXVXQ4KUUnq0="
