os:
  - MinGW

install:
  # Go To libnanomsg Destination Directory
  - cd ..
  # Download And Compile libnanomsg
  - ps: Start-FileDownload 'https://github.com/nanomsg/nanomsg/archive/0.9-beta.zip'
  - 7z x 0.9-beta.zip
  - cd nanomsg-0.9-beta
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target install
  #- SET PATH=%PATH%;C:\MinGW\bin
  #- echo Current dir is '%CD%'
  #- dir . /s
  #- mingw32-make.exe
  #- mingw32-make.exe install
  # Fix libnanomsg Library Directory Name
  # - mv .\Debug .\.libs
  # Return To nanomsg-rs Git Directory
  - cd ../../nanomsg-rs
  # Download And Install Rust
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.8.0-i686-pc-windows-msvc.msi'
  - start /wait msiexec /i  rust-1.8.0-i686-pc-windows-msvc.msi INSTALLDIR="C:\Program Files (x86)\Rust" /quiet /qn /passive /norestart
  - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build_script:
  - set LIB=%LIB%;C:\Program Files (x86)\nanomsg\lib
  - set PATH=%PATH%;C:\Program Files (x86)\nanomsg\bin
  - cargo build
 
test_script:
  - set LIB=%LIB%;C:\Program Files (x86)\nanomsg\lib
  - set PATH=%PATH%;C:\Program Files (x86)\nanomsg\bin
  - cargo test
  # Move libnanomsg To Test nanomsg_sys
  - mv ..\nanomsg-0.9-beta .\nanomsg-0.9-beta && cd nanomsg_sys
  - cargo test