os:
  - MinGW

install:
  # Go To libnanomsg Destination Directory
  - cd ..
  # Download And Compile libnanomsg
  - ps: Start-FileDownload 'https://github.com/nanomsg/nanomsg/releases/download/0.8-beta/nanomsg-0.8-beta.zip'
  - 7z x nanomsg-0.8-beta.zip
  - cd nanomsg-0.8-beta
  - cmake . && msbuild nanomsg.sln
  # Fix libnanomsg Library Directory Name
  - mv .\Debug .\.libs
  # Return To nanomsg-rs Git Directory
  - cd ..\nanomsg-rs
  # Download And Install Rust
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.6.0-i686-pc-windows-gnu.msi'
  - msiexec /i rust-1.6.0-i686-pc-windows-gnu.msi /passive /norestart
  - SET PATH=%PATH%;C:\MinGW\bin
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust stable 1.6\bin
  - dir "C:\Program Files (x86)"
  - dir "C:\Program Files"
  - gcc -v
  - rustc -V
  - cargo -V

build_script:
  - cargo build
 
test_script:
  - cargo test
  # Move libnanomsg To Test nanomsg_sys
  - mv ../nanomsg-0.8-beta ./nanomsg-0.8-beta && cd nanomsg_sys
  - cargo test