os:
  - MinGW

install:
  # Go To libnanomsg Destination Directory
  - cd ..
  # Download And Compile libnanomsg
  - ps: Start-FileDownload 'https://github.com/nanomsg/nanomsg/archive/0.9-beta.zip'
  - 7z x 0.9-beta.zip
  - cd nanomsg-0.9-beta
  - mkdir build
  - cd build
  - cmake ..
  - cmake -DNN_STATIC_LIB:BOOL=ON --build .
  - SET PATH=%PATH%;C:\MinGW\bin
  - make
  - make install
  # Fix libnanomsg Library Directory Name
  # - mv .\Debug .\.libs
  # Return To nanomsg-rs Git Directory
  - cd ..\..\nanomsg-rs
  # Download And Install Rust
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.8.0-x86_64-pc-windows-msvc.msi'
  - msiexec /i rust-1.8.0-x86_64-pc-windows-msvc.msi /passive /norestart
  - dir 'C:\Program Files (x86)'
  - dir ..\nanomsg-0.9-beta\build
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust stable GNU 1.6\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo build
 
test_script:
  - cargo test
  # Move libnanomsg To Test nanomsg_sys
  - mv ..\nanomsg-0.9-beta .\nanomsg-0.9-beta && cd nanomsg_sys
  - cargo test