[project]
name = "nanomsg"
version = "0.2.0"
authors = [
  "Daniel Fagnan <dnfagnan@gmail.com>",
  "Jason E. Aten",
  "David C. Bishop",
  "Dennis Lawler",
  "Zachary Tong",
  "Dan Burkert"
]

[dependencies.libnanomsg]
path = "libnanomsg"
